# Yml file to start the build of docker container via these services not but direct command.
version: "3.9"

services:
  # Service Name
  app:
    build:
      # building Current Directory (Current dir)
      context: .
      # For linting purposes.
      args:
        - DEV=true
    # Ports 8000 on local machine to 8000 on docker container
    ports:
      - "8000:8000"
    # Mapping dirs from systems to doc container
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
  # All the thing below this related to database services
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data: